# Generated by Django 6.0.2 on 2026-02-09 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(help_text='Short code for URLs (e.g., QC, PUR, UTIL).', max_length=40, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the department scope or function.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='UP', max_length=8)),
                ('status_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='downtime_tracker.department')),
            ],
            options={
                'ordering': ['department__name', 'asset_number'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=8)),
                ('to_status', models.CharField(max_length=8)),
                ('comment', models.TextField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='downtime_tracker.equipment')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_comment', models.TextField()),
                ('end_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_started', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_events', to='downtime_tracker.equipment')),
                ('ended_by_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_downtime_event', to='downtime_tracker.statuschangelog')),
                ('started_by_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_downtime_event', to='downtime_tracker.statuschangelog')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['department', 'status'], name='downtime_tr_departm_2b3f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['asset_number'], name='downtime_tr_asset_n_4c36a2_idx'),
        ),
        migrations.AddIndex(
            model_name='statuschangelog',
            index=models.Index(fields=['equipment', '-changed_at'], name='downtime_tr_equipme_40b7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='statuschangelog',
            index=models.Index(fields=['-changed_at'], name='downtime_tr_changed_c4b7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='downtimeevent',
            index=models.Index(fields=['equipment', '-started_at'], name='downtime_tr_equipme_cbaec6_idx'),
        ),
        migrations.AddIndex(
            model_name='downtimeevent',
            index=models.Index(fields=['ended_at'], name='downtime_tr_ended_a_16513c_idx'),
        ),
    ]
