# Generated by Django 6.0.2 on 2026-02-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtime_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statuschangelog',
            name='downtime_tr_equipme_40b7bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='statuschangelog',
            name='downtime_tr_changed_c4b7b5_idx',
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='category',
            field=models.CharField(choices=[('PLANNED', 'Calibration / Preventive Maintenance'), ('UNPLANNED', 'Unplanned')], db_index=True, default='UNPLANNED', max_length=12),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
